Fix compatibility with asyncio.timeout() on python 3.11+.
